### ISSUE TITLE
error: no member named 'regs' in 'struct pt_regs'

### ISSUE THREAD

**Issue by lxy417** [maiyao1988/ebpf-plugin#5]
<img width="672" alt="image" src="https://user-images.githubusercontent.com/33677809/205477023-609bacd9-9c79-4408-8a7b-bc9e5ad57cc0.png">
请问这是为什么

**Comment by maiyao1988** [comment]
内核版本是多少

**Comment by lxy417** [comment]
Linux localhost 5.10.136-android12-9-00005-gf9a66cbe7091-ab9177899 #1 SMP PREEMPT Fri Oct 14 05:14:18 UTC 2022 x86_64
我用的android 自带的模拟器， android12 x86_64的

**Comment by maiyao1988** [comment]
x86不支持，寄存器与arm完全不一样。
